/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          created_at?: parameters["rowFilter.Users.created_at"];
          name?: parameters["rowFilter.Users.name"];
          passwordHash?: parameters["rowFilter.Users.passwordHash"];
          userId?: parameters["rowFilter.Users.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Users */
          Users?: definitions["Users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          created_at?: parameters["rowFilter.Users.created_at"];
          name?: parameters["rowFilter.Users.name"];
          passwordHash?: parameters["rowFilter.Users.passwordHash"];
          userId?: parameters["rowFilter.Users.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          created_at?: parameters["rowFilter.Users.created_at"];
          name?: parameters["rowFilter.Users.name"];
          passwordHash?: parameters["rowFilter.Users.passwordHash"];
          userId?: parameters["rowFilter.Users.userId"];
        };
        body: {
          /** Users */
          Users?: definitions["Users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Users: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: text */
    name: string;
    /** Format: text */
    passwordHash: string;
    /** Format: uuid */
    userId: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Users */
  "body.Users": definitions["Users"];
  /** Format: bigint */
  "rowFilter.Users.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Users.created_at": string;
  /** Format: text */
  "rowFilter.Users.name": string;
  /** Format: text */
  "rowFilter.Users.passwordHash": string;
  /** Format: uuid */
  "rowFilter.Users.userId": string;
}

export interface operations {}

export interface external {}
